#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define CUSTOMHIDESETTINGSDLG                   111
#define ADVANCEDSETTINGS                        112
#define OLLYFIXES                               113
#define ANTIDBGTRICKS                           114
#define ABOUT                                   117
#define ABOUTBMP                                119
#define IDD_AADP4OLLY                           120
#define CHECK_FIXFLDZ                           1000
#define CHECK_TABADVSETTINGS_SELECTALL          1000
#define IDC_TAB1                                1000
#define LB_CONFIGLIST                           1000
#define CHECK_FIXFUISTQ                         1001
#define CHECK_FIXNUMBEROFRVA                    1002
#define CHECK_FIXFORMATSTRING                   1003
#define CHECK_FIXANALYSISCRASH                  1004
#define CHECK_TABFIXES_SELECTALL                1005
#define EDIT_NAME                               1008
#define CHECK_CTRLG                             1013
#define CHECK_EPOUTSIDECODE                     1014
#define CHECK_MOREPATCHES                       1015
#define CHECK_COMPRESSEDCODE                    1016
#define CHECK_LOADDLLWARNING                    1017
#define CHECK_MAXIMIZEOLLY                      1018
#define CHECK_BEINGDEBUGGED                     1023
#define CHECK_NTGLOBALFLAGS                     1024
#define CHECK_HEAPFLAGS                         1025
#define CHECK_FORCEFLAGS                        1026
#define CHECK_ZWQUERYOBJECT                     1027
#define CHECK_SETINFOTHREAD                     1028
#define CHECK_ZWOPENPROCESS                     1029
#define CHECK_ZWQUERYINFOPROCESS                1030
#define CHECK_ZWQUERYSYSINFO                    1031
#define CHECK_BLOCKINPUT                        1032
#define CHECK_SUSPENDTHREAD                     1033
#define CHECK_OUTPUTDEBUGSTRING                 1034
#define CHECK_MODULE32NEXT                      1035
#define CHECK_PROCESS32NEXT                     1036
#define CHECK_TERMINATEPROCESS                  1037
#define CHECK_GETTICKCOUNT                      1038
#define RADIO_NOCOUNTER                         1039
#define RADIO_COUNTERPLUSONE                    1040
#define RADIO_RANDOMCOUNTER                     1041
#define CHECK_RDTSC                             1042
#define CHECK_UNHANDLEDEXCEPTIONFILTER          1043
#define CHECK_FINDWINDOW                        1044
#define CHECK_MAXIMIZECHILDS                    1045
#define CHECK_SELECTALL                         1045
#define CHECK_SKIPEXCEPTIONS                    1046
#define CHECK_REALTIMEPATCHING                  1047
#define CHECK_BREAKONTLS                        1048
#define CHECK_ANTIANTIATTACH                    1049
#define CHECK_SINGLESTEPCOMPATIBILITY           1050
#define BT_APPLYCONFIG                          1052
#define BT_ADDCONFIG                            1053
#define BT_SAVECONFIG                           1055
#define BT_REMOVEFROMCONFIGLIST                 1057
